version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:80
    volumes:
      - ".:/var/www/html"
    ports:
      - "80:80"
      
  composer:
    image: composer
    command: composer install
    volumes:
      - ".:/app"